config/routes.rb
Rails.application.routes.draw do
  resources :myriads

end

app/models/myriad.rb
class Myriad < ActiveRecord::Base
  validates :name,
            presence: true,
            length: {in: 3..35}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/myriads_controller.rb
class MyriadsController < ApplicationController
  before_action :set_myriad, only: [:show, :edit, :update, :destroy]

  # GET /myriads
  # GET /myriads.json
  def index
    @myriads = Myriad.all
  end

  # GET /myriads/1
  # GET /myriads/1.json
  def show
  end

  # GET /myriads/new
  def new
    @myriad = Myriad.new
  end

  # GET /myriads/1/edit
  def edit
  end

  # POST /myriads
  # POST /myriads.json
  def create
    @myriad = Myriad.new(myriad_params)

    respond_to do |format|
      if @myriad.save
        format.html { redirect_to @myriad, notice: 'Myriad was successfully created.' }
        format.json { render :show, status: :created, location: @myriad }
      else
        format.html { render :new }
        format.json { render json: @myriad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /myriads/1
  # PATCH/PUT /myriads/1.json
  def update
    respond_to do |format|
      if @myriad.update(myriad_params)
        format.html { redirect_to @myriad, notice: 'Myriad was successfully updated.' }
        format.json { render :show, status: :ok, location: @myriad }
      else
        format.html { render :edit }
        format.json { render json: @myriad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myriads/1
  # DELETE /myriads/1.json
  def destroy
    @myriad.destroy
    respond_to do |format|
      format.html { redirect_to myriads_url, notice: 'Myriad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myriad
      @myriad = Myriad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def myriad_params
      params.require(:myriad).permit(:name, :race, :lat, :lng)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/myriads_helper.rb
module MyriadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyriamApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/myriads/_form.html.erb
<%= form_for(@myriad) do |f| %>
  <% if @myriad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myriad.errors.count, "error") %> prohibited this myriad from being saved:</h2>

      <ul>
      <% @myriad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/myriads/edit.html.erb
<h1>Editing Myriad</h1>

<%= render 'form' %>

<%= link_to 'Show', @myriad %> |
<%= link_to 'Back', myriads_path %>

app/views/myriads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Myriads</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @myriads.each do |myriad| %>
      <tr>
        <td><%= link_to 'Show', myriad %></td>
        <td><%= link_to 'Edit', edit_myriad_path(myriad) %></td>
        <td><%= link_to 'Destroy', myriad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Myriad', new_myriad_path %>

app/views/myriads/new.html.erb
<h1>New Myriad</h1>

<%= render 'form' %>

<%= link_to 'Back', myriads_path %>

app/views/myriads/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_myriad_path(@myriad) %> |
<%= link_to 'Back', myriads_path %>